theme: jekyll-theme-minimal

title: Douglas Lavin
description: I am Reader in Philosophy at University College London. I work in practical philosophy, especially ethics, history of ethics and action theory. 